"""contacts and user labels

Revision ID: 8d08caf0d288
Revises: fbcc579c4485
Create Date: 2026-08-28 17:04:03.753840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d08caf0d288'
down_revision: Union[str, None] = 'fbcc579c4485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=False),
    sa.Column('duty', sa.String(length=256), nullable=False),
    sa.Column('when_to_ask', sa.String(length=256), nullable=False),
    sa.Column('avatar_emoji', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_labels_contact_id'), 'user_labels', ['contact_id'], unique=False)
    op.create_index(op.f('ix_user_labels_user_id'), 'user_labels', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_labels_user_id'), table_name='user_labels')
    op.drop_index(op.f('ix_user_labels_contact_id'), table_name='user_labels')
    op.drop_table('user_labels')
    op.drop_table('contacts')
    # ### end Alembic commands ###
